from __future__ import annotations

from pathlib import Path
import os

INCLUDE_EXTENSIONS = {".py", ".md", ".txt", ".json", ".yaml", ".yml", ".toml", ".ini", ".cfg", ".xml", ".html", ".htm", ".css", ".js", ".ts", ".jsx", ".tsx", ".cmd", ".bat", ".ps1", ".cs", ".java", ".c", ".h", ".cpp", ".hpp", ".m", ".mat", ".mlx", ".slx"}
EXCLUDE_DIRS = {".git", ".hg", ".svn", "node_modules", "venv", ".venv", "env", "__pycache__", ".pytest_cache", ".mypy_cache", "dist", "build", "bin", "obj", "target", "coverage", "htmlcov", "downloads", "user_data_profile", "workflows"}
EXCLUDE_SUFFIXES = {".pyc", ".pyo", ".pyd", ".dll", ".exe", ".zip", ".7z", ".tar", ".gz", ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".pdf", ".docx", ".xlsx", ".pptx"}

def should_skip_dir(dirname: str) -> bool:
    return dirname in EXCLUDE_DIRS

def should_include_file(path: Path) -> tuple[bool, str]:
    suffix = path.suffix.lower()
    if suffix in EXCLUDE_SUFFIXES:
        return False, "excluded extension"
    if suffix not in INCLUDE_EXTENSIONS:
        return False, "unsupported extension"
    return True, "included"

def language_for_extension(path: Path) -> str:
    return {".py": "python", ".md": "markdown", ".json": "json", ".yaml": "yaml", ".yml": "yaml", ".xml": "xml", ".html": "html", ".htm": "html", ".css": "css", ".js": "javascript", ".ts": "typescript", ".jsx": "jsx", ".tsx": "tsx", ".cmd": "batch", ".bat": "batch", ".ps1": "powershell", ".cs": "csharp", ".java": "java", ".c": "c", ".h": "c", ".cpp": "cpp", ".hpp": "cpp", ".m": "matlab", ".toml": "toml", ".ini": "ini", ".cfg": "ini", ".txt": "text"}.get(path.suffix.lower(), "text")

def pack_codebase(repo_path: Path, output_path: Path, max_file_bytes: int = 100_000, max_total_bytes: int = 500_000) -> Path:
    repo_path = Path(repo_path).resolve()
    output_path = Path(output_path).resolve()
    included: list[Path] = []
    skipped: list[tuple[Path, str]] = []
    sections: list[str] = []
    total = 0
    truncated = False
    for root, dirnames, filenames in os.walk(repo_path):
        root_path = Path(root)
        dirnames[:] = sorted([d for d in dirnames if not should_skip_dir(d)])
        for filename in sorted(filenames):
            path = root_path / filename
            rel = path.relative_to(repo_path)
            include, reason = should_include_file(path)
            if not include:
                skipped.append((rel, reason))
                continue
            size = path.stat().st_size
            if size > max_file_bytes:
                skipped.append((rel, f"file too large ({size} bytes)"))
                continue
            if total + size > max_total_bytes:
                skipped.append((rel, "total pack limit reached"))
                truncated = True
                continue
            text = path.read_text(encoding="utf-8", errors="replace")
            included.append(rel)
            total += size
            sections.append(f"---\n\n## File: {rel.as_posix()}\n\n```{language_for_extension(path)}\n{text}\n```\n")
    header = ["# Packed Codebase", "", f"Repository: {repo_path}", "", "Generated by: codebase_pack.py", "", "## Packing Limits", "", f"- Max file bytes: {max_file_bytes}", f"- Max total bytes: {max_total_bytes}", f"- Total included source bytes: {total}", f"- Truncated: {'yes' if truncated else 'no'}", "", "## Included Files", ""]
    header.extend([f"- {p.as_posix()}" for p in included] or ["- None"])
    header.extend(["", "## Skipped Files", ""])
    header.extend([f"- {p.as_posix()} — {reason}" for p, reason in skipped] or ["- None"])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists():
        raise FileExistsError(f"Refusing to overwrite existing artifact: {output_path}")
    output_path.write_text("\n".join(header) + "\n\n" + "\n".join(sections), encoding="utf-8")
    return output_path
