"""Persisted workflow checkpoint models."""
from enum import StrEnum
class Checkpoint(StrEnum):
    NOT_STARTED="NOT_STARTED"; IN_PROGRESS="IN_PROGRESS"; SUBMISSION_CONFIRMED="SUBMISSION_CONFIRMED"; ARTIFACT_RECEIVED="ARTIFACT_RECEIVED"; VALIDATED="VALIDATED"; APPLIED="APPLIED"; COMPLETE="COMPLETE"; FAILED="FAILED"
FEATURE_STATES=("CREATED","PREPARING","CONTEXT_READY","TASK_READY","SCOPING","SCOPE_READY","IMPLEMENTING","IMPLEMENTED","REVIEWING","REPAIRING","VERIFICATION_READY","VERIFYING","VERIFIED","ACCEPTED","DELIVERING","DELIVERED","NEEDS_ACTION","FAILED","CANCELLED")
ISSUE_STATES=("CREATED","PREPARING","CONTEXT_READY","REPRODUCING","REPRODUCTION_READY","ANALYZING","ANALYSIS_READY","ANALYSIS_REVIEWING","SCOPE_READY","IMPLEMENTING","IMPLEMENTED","REVIEWING","REPAIRING","VERIFYING","VERIFIED","ACCEPTED","DELIVERED","NEEDS_ACTION","FAILED","CANCELLED")

def next_resume_action(checkpoint:Checkpoint)->str:
    return {Checkpoint.NOT_STARTED:"submit",Checkpoint.IN_PROGRESS:"inspect_submission",Checkpoint.SUBMISSION_CONFIRMED:"new_semantic_attempt",Checkpoint.ARTIFACT_RECEIVED:"validate_existing",Checkpoint.VALIDATED:"apply_in_attempt",Checkpoint.APPLIED:"regenerate_diff",Checkpoint.COMPLETE:"continue",Checkpoint.FAILED:"needs_action"}[checkpoint]
